spring:
  application:
    name: data-aggregator
  threads:
    virtual:
      enabled: true

aggregator:
  clients:
    user-service-base-url: https://api.example.com
    order-service-base-url: https://orders.example.com
    preference-graphql-url: https://preferences.example.com/graphql

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
